/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nth.smartcard.view;

import com.nth.smartcard.view.ChangePin;
import com.nth.smartcard.view.GUI;
import com.nth.smartcard.utils.VNCharacterUtils;
import com.nth.smartcard.utils.SmartCardWork;
import com.nth.smartcard.model.Infomation;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.nio.file.Files;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Nguyen Tien Hoa
 */
public class ChangeInfo extends javax.swing.JFrame {

    /**
     * Creates new form ChangeInfo
     */
    private byte[] byteImg;
    private final SmartCardWork card;
    private final GUI gui;
    private Infomation info;
    private ChangePin changePin;
    public ChangeInfo(SmartCardWork card, GUI gui) {
        this.card = card;
        this.gui = gui;
        initComponents();
        initInfo();
    }

    private void initInfo() {
        info = card.readInfo();
        if (info != null) {
            txt_fullName.setText(info.getFullName());
            txt_Khoa.setText(info.getKhoa());
            txt_Lop.setText(info.getLop());
            txt_maSV.setText(info.getMaSV());
            SmartCardWork.setImageIcon(info.getAvata(), lb_img_avatar);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb_img_avatar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_fullName = new javax.swing.JTextField();
        txt_Khoa = new javax.swing.JTextField();
        txt_Lop = new javax.swing.JTextField();
        txt_maSV = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btn_ChooseIMG = new javax.swing.JButton();
        btn_ChangeInfo = new javax.swing.JButton();
        btn_Cancel = new javax.swing.JButton();
        btn_ChangePin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lb_img_avatar.setBackground(new java.awt.Color(153, 255, 153));
        lb_img_avatar.setForeground(new java.awt.Color(153, 255, 153));
        lb_img_avatar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true));
        lb_img_avatar.setOpaque(true);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 204));
        jLabel3.setText("Họ Tên :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 204));
        jLabel4.setText("Khóa : ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 204));
        jLabel5.setText("Mã SV :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 204));
        jLabel6.setText("Lớp : ");

        txt_fullName.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_fullName.setForeground(new java.awt.Color(204, 0, 0));
        txt_fullName.setPreferredSize(new java.awt.Dimension(99, 30));

        txt_Khoa.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_Khoa.setForeground(new java.awt.Color(204, 0, 0));
        txt_Khoa.setPreferredSize(new java.awt.Dimension(99, 30));

        txt_Lop.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_Lop.setForeground(new java.awt.Color(204, 0, 0));
        txt_Lop.setPreferredSize(new java.awt.Dimension(99, 30));

        txt_maSV.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_maSV.setForeground(new java.awt.Color(204, 0, 0));
        txt_maSV.setPreferredSize(new java.awt.Dimension(99, 30));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_fullName, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Khoa, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Lop, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_maSV, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_fullName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Khoa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Lop, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_maSV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Cập nhật thông tin thẻ ");

        btn_ChooseIMG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_ChooseIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nth/smartcard/icon/icon-profile-25x25.png"))); // NOI18N
        btn_ChooseIMG.setText("Choose IMG");
        btn_ChooseIMG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ChooseIMGActionPerformed(evt);
            }
        });

        btn_ChangeInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_ChangeInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nth/smartcard/icon/icon-update-25x25.png"))); // NOI18N
        btn_ChangeInfo.setText("Update");
        btn_ChangeInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ChangeInfoActionPerformed(evt);
            }
        });

        btn_Cancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nth/smartcard/icon/cancel-25x25.png"))); // NOI18N
        btn_Cancel.setText("Cancel");
        btn_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelActionPerformed(evt);
            }
        });

        btn_ChangePin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_ChangePin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nth/smartcard/icon/icon_Reset_Password-25x25.png"))); // NOI18N
        btn_ChangePin.setText("Change Pin");
        btn_ChangePin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ChangePinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_img_avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btn_ChooseIMG)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_ChangeInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_ChangePin)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lb_img_avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_ChooseIMG, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_ChangeInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_ChangePin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ChooseIMGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ChooseIMGActionPerformed
        JFileChooser file = new JFileChooser();
        file.setDialogTitle("Chọn ảnh sinh vien");
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.images", "jpg", "png");
        file.addChoosableFileFilter(filter);
        int result = file.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            try {
                File selectedFile = file.getSelectedFile();
                String path = selectedFile.getAbsolutePath();
                lb_img_avatar.setIcon(SmartCardWork.resizeImageIcon(path, lb_img_avatar));
                byteImg = Files.readAllBytes(selectedFile.toPath());

            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Lỗi cover ảnh");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Chưa chọn được ảnh");
        }
    }//GEN-LAST:event_btn_ChooseIMGActionPerformed

    private void btn_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelActionPerformed

        this.dispose();
        gui.setVisible(true);
        gui.validate();

    }//GEN-LAST:event_btn_CancelActionPerformed

    private void btn_ChangeInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ChangeInfoActionPerformed
        try {
            if (byteImg == null) {
                byteImg = new byte[0];
            }
            if (byteImg.length >= 32000) {
                JOptionPane.showMessageDialog(null, "Ảnh có kích thước quá lớn");
            } else {
                String fullName = VNCharacterUtils.removeAccent(txt_fullName.getText().trim());
                String khoa = VNCharacterUtils.removeAccent(txt_Khoa.getText().trim());
                String lop = VNCharacterUtils.removeAccent(txt_Lop.getText().trim());
                String masv = VNCharacterUtils.removeAccent(txt_maSV.getText().trim());
                if (fullName.isEmpty() || khoa.isEmpty() || lop.isEmpty() || masv.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Cần nhập đủ thông tin");
                } else {
                    info = new Infomation(fullName, khoa, lop, masv, byteImg);
                    if (card.saveInfo(info)) {
                        gui.readInfomation();
                        this.dispose();
                        gui.setVisible(true);
                        gui.validate();
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Đã có lỗi xảy ra");
        }

    }//GEN-LAST:event_btn_ChangeInfoActionPerformed

    private void btn_ChangePinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ChangePinActionPerformed
        
         if (changePin == null) {
                changePin = new ChangePin(card, this,info);
                changePin.setVisible(true);
                changePin.validate();
                this.dispose();
            } else {
                changePin.setVisible(true);
                changePin.validate();
                this.dispose();
            }
        
        
    }//GEN-LAST:event_btn_ChangePinActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cancel;
    private javax.swing.JButton btn_ChangeInfo;
    private javax.swing.JButton btn_ChangePin;
    private javax.swing.JButton btn_ChooseIMG;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lb_img_avatar;
    private javax.swing.JTextField txt_Khoa;
    private javax.swing.JTextField txt_Lop;
    private javax.swing.JTextField txt_fullName;
    private javax.swing.JTextField txt_maSV;
    // End of variables declaration//GEN-END:variables
}
